server:
  port: 8080

spring:
  application:
    name: exodusent

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/exodusent}
    username: ${SPRING_DATASOURCE_USERNAME:exodusent}
    password: ${SPRING_DATASOURCE_PASSWORD:exodusent_dev}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
